## Import libraries

In [1]:
import pandas as pd
pd.options.mode.chained_assignment = None

In [2]:
import numpy as np
import os

## Import Data

In [3]:
#Table Final Commune
df_Vote = pd.read_excel(r"\Users\33629\Desktop\Presidentielle_2017_bourgogne_Tour_1 (1).xlsx", sheet_name = 'Feuil3')

In [4]:
#Indicateur de crime Mike
Indic_Crime_MK = pd.read_csv(r"C:\Users\33629\Desktop\data_mspr_bdd\Indice_crime_Mike.csv")

In [5]:
#Fichier Resultat 2022
df = pd.read_excel(r"\Users\33629\Desktop\resultat20221.xlsx", sheet_name = 'Résultats par niveau BurVot T1 ')

In [6]:
#Fichier Resultat 2017 
data = pd.read_csv(r"C:\Users\33629\Downloads\DATA_PY.csv",sep=';', encoding='utf-8' )

## Table Commune

In [8]:
df_Vote = df_Vote[['Libellé de la commune', 'Code du département']]

In [9]:
df_Vote['Votes_Nuls_2017'] = None

In [10]:
df_Vote['Votes_Nuls_2022'] = None

In [11]:
df_Vote['Inscrits_2017'] = None

In [12]:
df_Vote['Inscrits_2022'] = None

In [13]:
df_Vote['Droite_2017'] = None

In [14]:
df_Vote['Droite_2022'] = None

In [15]:
df_Vote['Gauche_2017'] = None

In [16]:
df_Vote['Gauche_2022'] = None

In [17]:
df_Vote['Milieu_2017'] = None

In [18]:
df_Vote['Milieu_2022'] = None

In [19]:
df_Vote['Gagnants_2017'] = None

In [20]:
df_Vote['Gagnants_2022'] = None

In [21]:
df_Vote['Partie_Gagnante_2017'] = None

In [22]:
df_Vote['Partie_Gagnante_2022'] = None

In [23]:
df_Vote['Indicateur_Emploi_2017'] = None

In [24]:
df_Vote['Indicateur_Emploi_2022'] = None

In [25]:
df_Vote['Indicateur_Crime'] = None

In [26]:
df_Vote

,Libellé de la commune,Code du département,Votes_Nuls_2017,Votes_Nuls_2022,Inscrits_2017,Inscrits_2022,Droite_2017,Droite_2022,Gauche_2017,Gauche_2022,Milieu_2017,Milieu_2022,Gagnants_2017,Gagnants_2022,Partie_Gagnante_2017,Partie_Gagnante_2022,Indicateur_Emploi_2017,Indicateur_Emploi_2022,Indicateur_Crime
0,Achun,58,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,Agencourt,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,Agey,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,Ahuy,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,Aignay-le-Duc,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2003,Voudenay,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2004,Vougeot,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2005,Voulaines-les-Templiers,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2006,Voutenay-sur-Cure,89,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2007,Yrouerre,89,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

## Indicateur de Criminalité

In [27]:
Indic_Crime_MK

    Code_département  indice_crim_final
0                  2           0.141054
1                 85           0.100943
2                 34           0.200364
3                 39           0.105300
4                 76           0.148495
..               ...                ...
96                 9           0.126616
97                80           0.151457
98               973           0.233210
99                18           0.122104
100               79           0.104711

[101 rows x 2 columns]

In [28]:
# Liste des codes de département que je veux filtrer
codes_departements = ['21', '58', '71', '89']

In [29]:
# Utilisation de la fonction .loc pour filtrer le DataFrame
Indice_MK_df = Indic_Crime_MK.loc[Indic_Crime_MK['Code_département'].isin(codes_departements)]

In [30]:
Indice_MK_df

   Code_département  indice_crim_final
16               89           0.141275
21               21           0.124492
86               58           0.115226
94               71           0.105812

In [31]:
# Convertir la colonne 'Code du département' dans df_Vote en objet (str)
df_Vote['Code du département'] = df_Vote['Code du département'].astype(str)

In [32]:
# Merge df_Vote et Indice_MK_df basé sur la colonne commune 'Code du département' dans df_Vote et 'Code_département' dans Indice_MK_df
merged_df = df_Vote.merge(Indice_MK_df[['Code_département', 'indice_crim_final']], left_on='Code du département', right_on='Code_département', how='left')

In [33]:
# Remplir la colonne 'Indice Crime' dans df_Vote avec les valeurs correspondantes de 'indice_crim_final' dans Indice_MK_df
df_Vote['Indicateur_Crime'] = merged_df['indice_crim_final']

In [34]:
df_Vote

,Libellé de la commune,Code du département,Votes_Nuls_2017,Votes_Nuls_2022,Inscrits_2017,Inscrits_2022,Droite_2017,Droite_2022,Gauche_2017,Gauche_2022,Milieu_2017,Milieu_2022,Gagnants_2017,Gagnants_2022,Partie_Gagnante_2017,Partie_Gagnante_2022,Indicateur_Emploi_2017,Indicateur_Emploi_2022,Indicateur_Crime
0,Achun,58,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.115226
1,Agencourt,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492
2,Agey,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492
3,Ahuy,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492
4,Aignay-le-Duc,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2003,Voudenay,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492
2004,Vougeot,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492
2005,Voulaines-les-Templiers,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492
2006,Voutenay-sur-Cure,89,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.141275
2007,Yrouerre,89,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.141275

In [35]:
#Vérification 

# Utilisation de la fonction .loc pour filtrer les données où la colonne 'Code du département' est égale à 21
donnees_21 = df_Vote.loc[df_Vote['Code du département'] == '21']

In [36]:
donnees_21

,Libellé de la commune,Code du département,Votes_Nuls_2017,Votes_Nuls_2022,Inscrits_2017,Inscrits_2022,Droite_2017,Droite_2022,Gauche_2017,Gauche_2022,Milieu_2017,Milieu_2022,Gagnants_2017,Gagnants_2022,Partie_Gagnante_2017,Partie_Gagnante_2022,Indicateur_Emploi_2017,Indicateur_Emploi_2022,Indicateur_Crime
1,Agencourt,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492
2,Agey,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492
3,Ahuy,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492
4,Aignay-le-Duc,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492
6,Aiserey,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2001,Vonges,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492
2002,Vosne-Romanée,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492
2003,Voudenay,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492
2004,Vougeot,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492
2005,Voulaines-les-Templiers,21,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.124492

In [37]:
result_df21 = df_Vote[(df_Vote['Code du département'] == 21) & (df_Vote['Indicateur_Crime'] != 0.124492)]

In [38]:
result_df21

Empty DataFrame
Columns: [Libellé de la commune, Code du département, Votes_Nuls_2017, Votes_Nuls_2022, Inscrits_2017, Inscrits_2022, Droite_2017, Droite_2022, Gauche_2017, Gauche_2022, Milieu_2017, Milieu_2022, Gagnants_2017, Gagnants_2022, Partie_Gagnante_2017, Partie_Gagnante_2022, Indicateur_Emploi_2017, Indicateur_Emploi_2022, Indicateur_Crime]
Index: []

## Resultats  2022

In [39]:
#Nettoyage du DataFrame en supprimant des colonnes spécifiques 
#et en regroupant certaines valeurs dans une nouvelle colonne appelée 'null'

df.drop(columns=df.columns[df.columns == ""], inplace=True)
df.drop(columns=["Libellé du département","Votants","% Vot/Ins","Libellé de la circonscription","Code du b.vote","% Voix/Ins.1","% Voix/Exp.1","% Voix/Ins.2","% Voix/Exp.2","% Voix/Ins.3","% Voix/Exp.3","% Voix/Ins.4","% Voix/Exp.4","% Voix/Ins.5","% Voix/Exp.5","% Voix/Ins.6","% Voix/Exp.6","% Voix/Ins.7","% Voix/Exp.7","% Voix/Ins.8","% Voix/Exp.8","% Voix/Ins.9","% Voix/Exp.9","% Voix/Ins.10","% Voix/Ins.11","% Voix/Exp.11","% Voix/Exp.10","Code de la circonscription","Code de la commune",'% Voix/Ins', 'Sexe','Sexe.1','Sexe.2','Sexe.3','Sexe.4','Sexe.5','Sexe.6','Sexe.7','Sexe.8','Sexe.9', 'Exprimés', "N°Panneau","N°Panneau.1","N°Panneau.2","N°Panneau.3","N°Panneau.4","N°Panneau.5","N°Panneau.6","N°Panneau.7","N°Panneau.8","% Voix/Exp","% Blancs/Ins","% Blancs/Vot","% Nuls/Ins","% Nuls/Vot","% Exp/Ins","% Exp/Vot","% Abs/Ins","d","N°Panneau.9","Sexe.10"], inplace=True)

df['null'] = df['Abstentions'] + df['Blancs'] + df['Nuls']
df.drop(columns=['Abstentions', 'Blancs', 'Nuls'], inplace=True)

In [40]:
#Ce code effectue une série d'opérations pour filtrer les colonnes contenant le mot 'Voix' dans leur nom,
#puis trouver les valeurs maximales dans chaque ligne pour ces colonnes. Ensuite,
#il récupère les valeurs des colonnes précédentes à celles contenant les valeurs maximales 
#et crée une nouvelle colonne 'gagnant(e)' pour stocker ces informations.


# Filtrer les colonnes contenant 'Nom' dans leur nom
colonnes_Voix = df.filter(like='Voix')
max_values = colonnes_Voix.max(axis=1)
idxmax_values = colonnes_Voix.idxmax(axis=1)

#for maxValCol in idxmax_values:
#    liste_colonnes = df.columns
#    preceding_column_id = df.columns.get_loc(maxValCol) - 1
#    print(preceding_column_id)
#    print(liste_colonnes[preceding_column_id])

df['gagnant(e)'] = ''
for i, maxValCol in enumerate(idxmax_values):
    liste_colonnes = df.columns
    preceding_column_id = df.columns.get_loc(maxValCol) - 1
    precedingg_column_id = df.columns.get_loc(maxValCol) - 2
    ligne = i
    colonne_a_modifier = liste_colonnes[preceding_column_id]
    colonne_a_modifier2 = liste_colonnes[precedingg_column_id]
    nouvelle_valeur = df.loc[ligne, colonne_a_modifier]
    nouvelle_valeur2 = df.loc[ligne, colonne_a_modifier2]
    #print(nouvelle_valeur)
    #print(maxValCol)
    df.loc[i, 'gagnant(e)'] = str(nouvelle_valeur) + ' ' + str(nouvelle_valeur2)

In [41]:
colonnes_prenom = df.filter(like='Prénom')
df = df.drop(columns=colonnes_prenom)
df.head(5)

,Code du département,Libellé de la commune,Inscrits,Nom,Voix,Nom.1,Voix.1,Nom.2,Voix.2,Nom.3,...,Nom.9,Voix.9,Nom.10,Voix.10,Nom.11,Voix.11,Unnamed: 103,131,null,gagnant(e)
0,01,L'Abergement-Clémenciat,645,ARTHAUD,3,ROUSSEL,6,MACRON,150,LASSALLE,...,PÉCRESSE,26,POUTOU,3,DUPONT-AIGNAN,21,NaN,NaN,125,Emmanuel MACRON
1,01,L'Abergement-de-Varey,213,ARTHAUD,2,ROUSSEL,7,MACRON,50,LASSALLE,...,PÉCRESSE,8,POUTOU,3,DUPONT-AIGNAN,0,NaN,NaN,42,Emmanuel MACRON
2,01,Ambérieu-en-Bugey,1129,ARTHAUD,4,ROUSSEL,30,MACRON,159,LASSALLE,...,PÉCRESSE,40,POUTOU,8,DUPONT-AIGNAN,13,NaN,NaN,289,Marine LE PEN
3,01,Ambérieu-en-Bugey,1128,ARTHAUD,6,ROUSSEL,13,MACRON,201,LASSALLE,...,PÉCRESSE,42,POUTOU,4,DUPONT-AIGNAN,20,NaN,NaN,286,Marine LE PEN
4,01,Ambérieu-en-Bugey,1213,ARTHAUD,8,ROUSSEL,18,MACRON,229,LASSALLE,...,PÉCRESSE,35,POUTOU,3,DUPONT-AIGNAN,19,NaN,NaN,264,Emmanuel MACRON

In [42]:
orientations_politiques = {
    "ARTHAUD": "gauche",
    "HIDALGO": "gauche",
    "JADOT": "gauche",
    "LASSALLE": "gauche",
    "MÉLENCHON": "gauche",
    "POUTOU": "gauche",
    "ROUSSEL": "gauche",
    "DUPONT-AIGNAN": "droite",
    "LE PEN": "droite",
    "PÉCRESSE": "droite",
    "ZEMMOUR": "droite",
    "MACRON": "milieu",

}

# Filtrer les colonnes contenant 'Nom' dans leur nom
colonnes_nom = df.filter(like='Nom')



# Créer un dictionnaire de correspondance pour le renommage des colonnes
column_mapping = {}
for colonne in colonnes_nom.columns:
    candidat = df.at[1, colonne]
    if candidat in orientations_politiques:
        orientation = orientations_politiques[candidat]
        column_mapping[colonne] = orientation




# Convertir les ensembles en listes
column_mapping = {str(k): str(v) for k, v in column_mapping.items()}

# Renommer les colonnes à l'aide de df.rename()
df.rename(columns=column_mapping, inplace=True)
df.head(5)

,Code du département,Libellé de la commune,Inscrits,gauche,Voix,gauche,Voix.1,milieu,Voix.2,gauche,...,droite,Voix.9,gauche,Voix.10,droite,Voix.11,Unnamed: 103,131,null,gagnant(e)
0,01,L'Abergement-Clémenciat,645,ARTHAUD,3,ROUSSEL,6,MACRON,150,LASSALLE,...,PÉCRESSE,26,POUTOU,3,DUPONT-AIGNAN,21,NaN,NaN,125,Emmanuel MACRON
1,01,L'Abergement-de-Varey,213,ARTHAUD,2,ROUSSEL,7,MACRON,50,LASSALLE,...,PÉCRESSE,8,POUTOU,3,DUPONT-AIGNAN,0,NaN,NaN,42,Emmanuel MACRON
2,01,Ambérieu-en-Bugey,1129,ARTHAUD,4,ROUSSEL,30,MACRON,159,LASSALLE,...,PÉCRESSE,40,POUTOU,8,DUPONT-AIGNAN,13,NaN,NaN,289,Marine LE PEN
3,01,Ambérieu-en-Bugey,1128,ARTHAUD,6,ROUSSEL,13,MACRON,201,LASSALLE,...,PÉCRESSE,42,POUTOU,4,DUPONT-AIGNAN,20,NaN,NaN,286,Marine LE PEN
4,01,Ambérieu-en-Bugey,1213,ARTHAUD,8,ROUSSEL,18,MACRON,229,LASSALLE,...,PÉCRESSE,35,POUTOU,3,DUPONT-AIGNAN,19,NaN,NaN,264,Emmanuel MACRON

In [43]:
colonnes = df.columns.tolist()

# colonnes = df.columns.tolist()

# Trouver les index de toutes les colonnes ayant le nom "gauche"
index_colonnes_gauche = [i for i, nom_colonne in enumerate(colonnes) if nom_colonne == 'gauche']
df['la gauche'] = 0
for colonne_gauche in index_colonnes_gauche:
    liste_colonnes = df.columns
    nom_colonne_recherchee = liste_colonnes[colonne_gauche + 1]
    df['la gauche'] += df[nom_colonne_recherchee]

df.drop(df.columns[index_colonnes_gauche], axis=1, inplace=True)

    
index_colonnes_droite = [i for i, nom_colonne in enumerate(df.columns) if nom_colonne == 'droite']
df['la droite'] = 0
for colonne_droite in index_colonnes_droite:
    liste_colonnes = df.columns
    nom_colonne_recherchee = liste_colonnes[colonne_droite + 1]
    df['la droite'] += df[nom_colonne_recherchee]
    
df.drop(df.columns[index_colonnes_droite], axis=1, inplace=True)


# Trouver les index de toutes les colonnes ayant le nom "gauche"
index_colonnes_centre = [i for i, nom_colonne in enumerate(colonnes) if nom_colonne == 'milieu']
index_colonne_milieu = df.columns.get_loc('milieu')
nom_colonne_recherchee = liste_colonnes[index_colonne_milieu + 1]
df['milieu'] = df[nom_colonne_recherchee]

df.drop(columns=["Voix","Voix.1","Voix.2","Voix.3","Voix.4","Voix.5","Voix.6","Voix.7","Voix.8","Voix.9","Voix.10","Voix.11"], inplace=True)

df.head(1)

,Code du département,Libellé de la commune,Inscrits,milieu,Unnamed: 103,131,null,gagnant(e),la gauche,la droite
0,01,L'Abergement-Clémenciat,645,150,NaN,NaN,125,Emmanuel MACRON,131,239

In [44]:
df.head(10)

,Code du département,Libellé de la commune,Inscrits,milieu,Unnamed: 103,131,null,gagnant(e),la gauche,la droite
0,01,L'Abergement-Clémenciat,645,150,NaN,NaN,125,Emmanuel MACRON,131,239
1,01,L'Abergement-de-Varey,213,50,NaN,NaN,42,Emmanuel MACRON,76,45
2,01,Ambérieu-en-Bugey,1129,159,NaN,NaN,289,Marine LE PEN,322,359
3,01,Ambérieu-en-Bugey,1128,201,NaN,NaN,286,Marine LE PEN,301,340
4,01,Ambérieu-en-Bugey,1213,229,NaN,NaN,264,Emmanuel MACRON,365,355
5,01,Ambérieu-en-Bugey,933,156,NaN,NaN,236,Jean-Luc MÉLENCHON,270,271
6,01,Ambérieu-en-Bugey,1047,132,NaN,NaN,340,Jean-Luc MÉLENCHON,312,263
7,01,Ambérieu-en-Bugey,1152,175,NaN,NaN,296,Jean-Luc MÉLENCHON,335,346
8,01,Ambérieu-en-Bugey,1034,189,NaN,NaN,258,Emmanuel MACRON,251,336
9,01,Ambérieu-en-Bugey,1129,212,NaN,NaN,243,Marine LE PEN,278,396

In [45]:
# Filtrer les colonnes contenant 'Nom' dans leur nom
max_values =  df[['la gauche', 'la droite', 'milieu']].idxmax(axis=1)

df['Bord politique gagnant'] = ''
for i, maxValCol in enumerate(max_values):
    liste_colonnes = df.columns
    ligne = i
    nouvelle_valeur = df.loc[ligne, maxValCol]
    #print(nouvelle_valeur)
    df.loc[i, 'Bord politique gagnant'] = str(maxValCol)


df.head(10)

,Code du département,Libellé de la commune,Inscrits,milieu,Unnamed: 103,131,null,gagnant(e),la gauche,la droite,Bord politique gagnant
0,01,L'Abergement-Clémenciat,645,150,NaN,NaN,125,Emmanuel MACRON,131,239,la droite
1,01,L'Abergement-de-Varey,213,50,NaN,NaN,42,Emmanuel MACRON,76,45,la gauche
2,01,Ambérieu-en-Bugey,1129,159,NaN,NaN,289,Marine LE PEN,322,359,la droite
3,01,Ambérieu-en-Bugey,1128,201,NaN,NaN,286,Marine LE PEN,301,340,la droite
4,01,Ambérieu-en-Bugey,1213,229,NaN,NaN,264,Emmanuel MACRON,365,355,la gauche
5,01,Ambérieu-en-Bugey,933,156,NaN,NaN,236,Jean-Luc MÉLENCHON,270,271,la droite
6,01,Ambérieu-en-Bugey,1047,132,NaN,NaN,340,Jean-Luc MÉLENCHON,312,263,la gauche
7,01,Ambérieu-en-Bugey,1152,175,NaN,NaN,296,Jean-Luc MÉLENCHON,335,346,la droite
8,01,Ambérieu-en-Bugey,1034,189,NaN,NaN,258,Emmanuel MACRON,251,336,la droite
9,01,Ambérieu-en-Bugey,1129,212,NaN,NaN,243,Marine LE PEN,278,396,la droite

In [46]:
# Liste des codes du département à filtrer
df = df[(df['Code du département'] == '21') | (df['Code du département'] == '58') | (df['Code du département'] == '71') | (df['Code du département'] == '89')]

df

,Code du département,Libellé de la commune,Inscrits,milieu,Unnamed: 103,131,null,gagnant(e),la gauche,la droite,Bord politique gagnant
11662,21,Agencourt,323,73,NaN,NaN,74,Emmanuel MACRON,86,90,la droite
11663,21,Agey,244,45,NaN,NaN,51,Jean-Luc MÉLENCHON,99,49,la gauche
11664,21,Ahuy,618,156,NaN,NaN,164,Emmanuel MACRON,99,199,la droite
11665,21,Ahuy,659,188,NaN,NaN,98,Emmanuel MACRON,169,204,la droite
11666,21,Aignay-le-Duc,240,65,NaN,NaN,64,Emmanuel MACRON,32,79,la droite
...,...,...,...,...,...,...,...,...,...,...,...
62382,89,Vireaux,88,8,NaN,NaN,34,Marine LE PEN,12,34,la droite
62383,89,Viviers,103,39,NaN,NaN,17,Emmanuel MACRON,9,38,milieu
62384,89,Voisines,405,68,NaN,NaN,105,Marine LE PEN,80,152,la droite
62385,89,Voutenay-sur-Cure,156,34,NaN,NaN,32,Marine LE PEN,31,59,la droite
62386,89,Yrouerre,144,21,NaN,NaN,45,Marine LE PEN,32,46,la droite

In [47]:
# Merge df_Vote et df basé sur la colonne commune 'Libellé de la commune' dans df_Vote et 'Libellé de la commune' dans df
merged_df2 = df_Vote.merge(df[['Libellé de la commune', 'Inscrits','milieu','null','gagnant(e)','la gauche','la droite','Bord politique gagnant']], left_on='Libellé de la commune', right_on='Libellé de la commune', how='left')

In [48]:
# Remplir les colonnes dans df_Vote avec les valeurs correspondantes dans df
df_Vote['Votes_Nuls_2022'] = merged_df2['null']
df_Vote['Inscrits_2022'] = merged_df2['Inscrits']
df_Vote['Droite_2022'] = merged_df2['la droite']
df_Vote['Gauche_2022'] = merged_df2['la gauche']
df_Vote['Milieu_2022'] = merged_df2['milieu']
df_Vote['Gagnants_2022'] = merged_df2['gagnant(e)']
df_Vote['Partie_Gagnante_2022'] = merged_df2['Bord politique gagnant']

In [49]:
df_Vote.head(3)

,Libellé de la commune,Code du département,Votes_Nuls_2017,Votes_Nuls_2022,Inscrits_2017,Inscrits_2022,Droite_2017,Droite_2022,Gauche_2017,Gauche_2022,Milieu_2017,Milieu_2022,Gagnants_2017,Gagnants_2022,Partie_Gagnante_2017,Partie_Gagnante_2022,Indicateur_Emploi_2017,Indicateur_Emploi_2022,Indicateur_Crime
0,Achun,58,None,26.0,None,105.0,None,47.0,None,18.0,None,14.0,None,Marine LE PEN,None,la droite,None,None,0.115226
1,Agencourt,21,None,74.0,None,323.0,None,90.0,None,86.0,None,73.0,None,Emmanuel MACRON,None,la droite,None,None,0.124492
2,Agey,21,None,51.0,None,244.0,None,49.0,None,99.0,None,45.0,None,Jean-Luc MÉLENCHON,None,la gauche,None,None,0.124492

In [50]:
# Convertir les colonnes en nombres entiers en supprimant le suffixe ".0" et gérer les valeurs non finies.
columns_to_convert = ['Votes_Nuls_2022', 'Inscrits_2022', 'Droite_2022', 'Milieu_2022','Gauche_2022']
df_Vote[columns_to_convert] = df_Vote[columns_to_convert].apply(pd.to_numeric, errors='coerce').fillna(0).astype(int)

In [51]:
df_Vote

,Libellé de la commune,Code du département,Votes_Nuls_2017,Votes_Nuls_2022,Inscrits_2017,Inscrits_2022,Droite_2017,Droite_2022,Gauche_2017,Gauche_2022,Milieu_2017,Milieu_2022,Gagnants_2017,Gagnants_2022,Partie_Gagnante_2017,Partie_Gagnante_2022,Indicateur_Emploi_2017,Indicateur_Emploi_2022,Indicateur_Crime
0,Achun,58,None,26,None,105,None,47,None,18,None,14,None,Marine LE PEN,None,la droite,None,None,0.115226
1,Agencourt,21,None,74,None,323,None,90,None,86,None,73,None,Emmanuel MACRON,None,la droite,None,None,0.124492
2,Agey,21,None,51,None,244,None,49,None,99,None,45,None,Jean-Luc MÉLENCHON,None,la gauche,None,None,0.124492
3,Ahuy,21,None,164,None,618,None,199,None,99,None,156,None,Emmanuel MACRON,None,la droite,None,None,0.124492
4,Aignay-le-Duc,21,None,98,None,659,None,204,None,169,None,188,None,Emmanuel MACRON,None,la droite,None,None,0.124492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2003,Voudenay,21,None,193,None,766,None,228,None,166,None,179,None,Emmanuel MACRON,None,la droite,None,None,0.124492
2004,Vougeot,21,None,157,None,649,None,184,None,162,None,146,None,Emmanuel MACRON,None,la droite,None,None,0.124492
2005,Voulaines-les-Templiers,21,None,39,None,192,None,59,None,26,None,68,None,Emmanuel MACRON,None,milieu,None,None,0.124492
2006,Voutenay-sur-Cure,89,None,20,None,69,None,28,None,16,None,5,None,Marine LE PEN,None,la droite,None,None,0.141275
2007,Yrouerre,89,None,76,None,385,None,158,None,79,None,72,None,Marine LE PEN,None,la droite,None,None,0.141275

## Resultats  2017

In [52]:
data['null'] = data['Abstentions'] + data['Blancs'] + data['Nuls']
data.drop(columns=['Abstentions', 'Blancs', 'Nuls'], inplace=True)

In [53]:
data

,id,Code_du_département,Libellé_du_département,Code_de_la_commune,Libellé_de_la_commune,Inscrits,__Abs_Ins,Votants,__Vot_Ins,__Blancs_Ins,...,__Voix_Ins_9,__Voix_Exp_9,N_Panneau_10,Sexe_10,Nom_10,Prénom_10,Voix_10,__Voix_Ins_10,__Voix_Exp_10,null
0,1,58,Nièvre,1,Achun,108,9.26,98,90.74,0.93,...,0.93,1.09,7,M,CHEMINADE,Jacques,0,0.0,0.00,16
1,2,21,Côte-d'Or,1,Agencourt,320,13.44,277,86.56,0.94,...,0.94,1.11,7,M,CHEMINADE,Jacques,0,0.0,0.00,49
2,3,21,Côte-d'Or,2,Agey,252,14.68,215,85.32,1.19,...,0.00,0.00,7,M,CHEMINADE,Jacques,0,0.0,0.00,42
3,4,21,Côte-d'Or,3,Ahuy,1000,14.90,851,85.10,1.00,...,0.30,0.36,7,M,CHEMINADE,Jacques,1,0.1,0.12,164
4,5,21,Côte-d'Or,4,Aignay-le-Duc,248,23.39,190,76.61,0.81,...,0.81,1.06,7,M,CHEMINADE,Jacques,1,0.4,0.53,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2003,2004,21,Côte-d'Or,715,Voudenay,171,22.81,132,77.19,1.17,...,0.00,0.00,10,M,ASSELINEAU,François,0,0.0,0.00,41
2004,2005,21,Côte-d'Or,716,Vougeot,162,16.67,135,83.33,4.32,...,0.00,0.00,10,M,ASSELINEAU,François,0,0.0,0.00,36
2005,2006,21,Côte-d'Or,717,Voulaines-les-Templiers,248,21.37,195,78.63,0.81,...,0.00,0.00,10,M,ASSELINEAU,François,0,0.0,0.00,56
2006,2007,89,Yonne,485,Voutenay-sur-Cure,152,17.76,125,82.24,1.32,...,0.00,0.00,10,M,ASSELINEAU,François,0,0.0,0.00,32
2007,2008,89,Yonne,486,Yrouerre,149,22.15,116,77.85,1.34,...,0.00,0.00,10,M,ASSELINEAU,François,0,0.0,0.00,35

In [54]:
orientations_politiques = {
    "DUPONT-AIGNAN": "droite",
    "LE PEN": "droite",
    "MACRON": "milieu",
    "HAMON": "gauche",
    "ARTHAUD": "gauche",
    "POUTOU": "gauche",
    "CHEMINADE": "milieu",
    "LASSALLE": "gauche",
    "ASSELINEAU": "droite",
    "FILLON": "droite",
    "MÉLENCHON": "gauche"
}
condidates_array = [voix.split("_")[1] for voix in data.columns if "Voix" in voix and "Ins" not in voix and "Exp" not in voix]
def getWinner(df_2017):
    maximum = 0
    condidate = False
    
    partie = {
        "droite" : 0,
        "gauche" : 0,
        "milieu" : 0
    }
     
    for i in condidates_array:
        if maximum < df_2017["Voix_"+i]:
            maximum = df_2017["Voix_"+i]
            condidate = df_2017["Nom_"+i]
        
        for p in partie:
            if orientations_politiques[df_2017["Nom_"+i]] == p : 
                partie[p] = partie[p] + df_2017["Voix_"+i]
        
    df_2017["Gagnant"] = condidate
    df_2017["Partie gagnante"] = max(partie, key=partie.get)
    for p in partie:
        df_2017[p] = partie[p]
            
    return df_2017

In [55]:
data = data.apply(getWinner, axis=1)[["Code_de_la_commune", "Libellé_de_la_commune", "Gagnant", "Partie gagnante", "droite", "gauche","milieu","Inscrits","null"]]

In [56]:
data

,Code_de_la_commune,Libellé_de_la_commune,Gagnant,Partie gagnante,droite,gauche,milieu,Inscrits,null
0,1,Achun,LE PEN,droite,47,25,20,108,16
1,1,Agencourt,LE PEN,droite,135,74,62,320,49
2,2,Agey,MACRON,droite,82,72,56,252,42
3,3,Ahuy,FILLON,droite,441,161,234,1000,164
4,4,Aignay-le-Duc,FILLON,droite,115,33,40,248,60
...,...,...,...,...,...,...,...,...,...
2003,715,Voudenay,LE PEN,droite,79,29,22,171,41
2004,716,Vougeot,FILLON,droite,65,35,26,162,36
2005,717,Voulaines-les-Templiers,LE PEN,droite,110,41,41,248,56
2006,485,Voutenay-sur-Cure,LE PEN,droite,66,26,28,152,32
2007,486,Yrouerre,LE PEN,droite,72,15,27,149,35

In [57]:
# Merge df_Vote et data basé sur la colonne commune 'Libellé de la commune' dans df_Vote et 'Libellé_de_la_commune' dans data
merged_2017 = df_Vote.merge(data[['Libellé_de_la_commune', 'Inscrits','milieu','null','Gagnant','gauche','droite','Partie gagnante']], left_on='Libellé de la commune', right_on='Libellé_de_la_commune', how='left')

In [58]:
# Remplir les colonnes dans df_Vote avec les valeurs correspondantes dans data
df_Vote['Votes_Nuls_2017'] = merged_2017['null']
df_Vote['Inscrits_2017'] = merged_2017['Inscrits']
df_Vote['Droite_2017'] = merged_2017['droite']
df_Vote['Gauche_2017'] = merged_2017['gauche']
df_Vote['Milieu_2017'] = merged_2017['milieu']
df_Vote['Gagnants_2017'] = merged_2017['Gagnant']
df_Vote['Partie_Gagnante_2017'] = merged_2017['Partie gagnante']

In [59]:
# Remplacer les valeurs dans la colonne 'Partie_Gagnante_2022'
mapping = {'la droite': 'droite', 'la gauche': 'gauche'}
df_Vote['Partie_Gagnante_2022'] = df_Vote['Partie_Gagnante_2022'].replace(mapping)

In [60]:
df_Vote.head(3)

,Libellé de la commune,Code du département,Votes_Nuls_2017,Votes_Nuls_2022,Inscrits_2017,Inscrits_2022,Droite_2017,Droite_2022,Gauche_2017,Gauche_2022,Milieu_2017,Milieu_2022,Gagnants_2017,Gagnants_2022,Partie_Gagnante_2017,Partie_Gagnante_2022,Indicateur_Emploi_2017,Indicateur_Emploi_2022,Indicateur_Crime
0,Achun,58,16,26,108,105,47,47,25,18,20,14,LE PEN,Marine LE PEN,droite,droite,None,None,0.115226
1,Agencourt,21,49,74,320,323,135,90,74,86,62,73,LE PEN,Emmanuel MACRON,droite,droite,None,None,0.124492
2,Agey,21,42,51,252,244,82,49,72,99,56,45,MACRON,Jean-Luc MÉLENCHON,droite,gauche,None,None,0.124492

## Indicateur d'Emploi

In [61]:
pip install xlrd

Requirement already satisfied: xlrd in c:\users\33629\anaconda3\anaconda_tp\lib\site-packages (2.0.1)
Note: you may need to restart the kernel to use updated packages.

In [63]:
import pandas as pd

def calculeActifParDep():

    file_path = 'estim-pop-dep-sexe-gca-1975-2023.xls'
    df2017 = pd.read_excel(file_path,"2017",skiprows=3, header=[0, 1], nrows=96)
    df2022 = pd.read_excel(file_path,"2022",skiprows=3, header=[0, 1], nrows=96)

    subset_columns = [('Départements', 'Unnamed: 0_level_1'),
                            ('Départements', 'Unnamed: 1_level_1'),
                            ('Ensemble', '20 à 39 ans'),
                            ('Ensemble', '40 à 59 ans')]


    df2022=df2022[subset_columns]
    df2017=df2017[subset_columns]

    df2017 = df2017.assign(Total_Actif=df2017[('Ensemble', '20 à 39 ans')] + df2017[('Ensemble', '40 à 59 ans')])
    df2022 = df2022.assign(Total_Actif=df2022[('Ensemble', '20 à 39 ans')] + df2022[('Ensemble', '40 à 59 ans')])

    df2017.drop(columns=[('Ensemble', '20 à 39 ans'), ('Ensemble', '40 à 59 ans')], inplace=True)
    df2022.drop(columns=[('Ensemble', '20 à 39 ans'), ('Ensemble', '40 à 59 ans')], inplace=True)

    
    df2022['Départements_fusionnes'] = df2022.apply(fusionner_departements, axis=1)

    df2022.drop(columns=[('Départements', 'Unnamed: 0_level_1'), ('Départements', 'Unnamed: 1_level_1')], inplace=True)

    df2017['Départements_fusionnes'] = df2017.apply(fusionner_departements, axis=1)

    df2017.drop(columns=[('Départements', 'Unnamed: 0_level_1'), ('Départements', 'Unnamed: 1_level_1')], inplace=True)

    departements_inclus = ['89', '21', '71', '58']

    df2017_filtered = df2017[df2017['Départements_fusionnes'].str[:2].isin(departements_inclus)]
    df2022_filtered = df2022[df2022['Départements_fusionnes'].str[:2].isin(departements_inclus)]
    return fusionner_dataframe(df2017_filtered,df2022_filtered)


def fusionner_dataframe(df_2017, df_2022):

    df_2017['Mois'] = 2017
    df_2022['Mois'] = 2022

    merged_df_emploi = pd.concat([df_2017, df_2022])

    pivot_df_emploi = merged_df_emploi.pivot(index='Mois', columns='Départements_fusionnes', values='Total_Actif')

    pivot_df_emploi.reset_index(inplace=True)

    pivot_df_emploi.columns.name = None

    new_columns = ['Mois'] + [f'{col.split(" ")[-1]} {col.split(" ")[0]}' for col in pivot_df_emploi.columns[1:]]
    pivot_df_emploi.columns = new_columns
    return pivot_df_emploi



def fusionner_departements(row):
    departement1 = row[('Départements', 'Unnamed: 0_level_1')]
    departement2 = row[('Départements', 'Unnamed: 1_level_1')]
    return f"{departement1} {departement2}"

def calculeMoyenneDemandeurParAnParDep():
    data_emploi = pd.read_csv('Demandeur_Emploie.csv', skiprows=3, delimiter=';', nrows=330)
    annee = ["1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023"]

    nouvelles_colonnes = {}
    for colonne in data_emploi.columns[:-1]:  
        nouvelles_colonnes[colonne] = []

    df_emploi = pd.DataFrame(nouvelles_colonnes)

    df_emploi['Mois'] = annee

    for col in data_emploi.columns[1:-1]:
        listeMoyenne=[]
        cpt = 1
        moyenne = 0
        for valeur in data_emploi[col]:
            moyenne += int(valeur.replace(" ", ""))
            if(cpt%12==0):
                listeMoyenne.append(moyenne//12)
                moyenne=0
            if(data_emploi.iloc[(cpt-1),0]=="Juin 2023"):
                listeMoyenne.append(moyenne//6)
            cpt+=1
        df_emploi[col]=listeMoyenne

    colonnes_desirees = ["Mois", "Côte-d'Or 21", "Yonne 89", "Nièvre 58", "Saône-et-Loire 71"]
    df_emploi = df_emploi[colonnes_desirees]

    annees_desirees = ["2017", "2022"]
    df_emploi = df_emploi[df_emploi['Mois'].isin(annees_desirees)]

    df_emploi = df_emploi.reset_index(drop=True)

    sorted_columns = ['Mois'] + sorted(df_emploi.columns[1:], key=extract_dept_number)
    df_sorted = df_emploi[sorted_columns]
    return df_sorted

def extract_dept_number(column_name):
    return int(column_name.split()[-1])

def indicateurParDep(df_2017,df_2022):
    df_2017_values = df_2017.drop(columns='Mois')
    df_2022_values = df_2022.drop(columns='Mois')

    result_values = df_2022_values.divide(df_2017_values)
    result_values = result_values*100

    result_df = pd.concat([df_2022['Mois'], result_values], axis=1)
    print(result_df)
    return result_df

df1 = calculeActifParDep()
df2 = calculeMoyenneDemandeurParAnParDep()
print(df1)
print(df2)
final = indicateurParDep(df1,df2)

   Mois  Côte-d'Or 21  Nièvre 58  Saône-et-Loire 71  Yonne 89
0  2017        268574      91049             254901    157342
1  2022        264654      84155             244629    149868
   Mois  Côte-d'Or 21  Nièvre 58  Saône-et-Loire 71  Yonne 89
0  2017         45909      16208              48993     29374
1  2022         42322      14124              45657     26865
   Mois  Côte-d'Or 21  Nièvre 58  Saône-et-Loire 71   Yonne 89
0  2017     17.093613  17.801404          19.220403  18.668887
1  2022     15.991445  16.783316          18.663772  17.925775

In [64]:
final

   Mois  Côte-d'Or 21  Nièvre 58  Saône-et-Loire 71   Yonne 89
0  2017     17.093613  17.801404          19.220403  18.668887
1  2022     15.991445  16.783316          18.663772  17.925775

In [75]:
#Indicateur d'emploi 2017
Indic_Emploi_2017 = pd.read_excel(r"C:\Users\33629\Desktop\data_mspr_bdd\Indicateur_Emploi_divis.xlsx", sheet_name = '2017')

In [76]:
Indic_Emploi_2017

   Code du département  Indic_2017
0                   21   17.093613
1                   58   17.801404
2                   71   19.220403
3                   89   18.668887

In [78]:
df_Vote['Code du département'] = df_Vote['Code du département'].astype(str)
Indic_Emploi_2017['Code du département'] = Indic_Emploi_2017['Code du département'].astype(str)

# Merge df_Vote et Indic_Emploi_2017 basé sur la colonne 'Code du département' dans df_Vote et 'Code du département' dans Indic_Emploi_2017
pivot_2017_emploi = df_Vote.merge(Indic_Emploi_2017[['Code du département', 'Indic_2017']], on='Code du département', how='left')

In [79]:
# Remplir la colonne 'Indicateur_Emploi_2017' dans df_Vote avec les valeurs correspondantes de 'Indic_2017' dans Indic_Emploi_2017
df_Vote['Indicateur_Emploi_2017'] = pivot_2017_emploi['Indic_2017']

In [81]:
df_Vote.head(3)

,Libellé de la commune,Code du département,Votes_Nuls_2017,Votes_Nuls_2022,Inscrits_2017,Inscrits_2022,Droite_2017,Droite_2022,Gauche_2017,Gauche_2022,Milieu_2017,Milieu_2022,Gagnants_2017,Gagnants_2022,Partie_Gagnante_2017,Partie_Gagnante_2022,Indicateur_Emploi_2017,Indicateur_Emploi_2022,Indicateur_Crime
0,Achun,58,16,26,108,105,47,47,25,18,20,14,LE PEN,Marine LE PEN,droite,droite,17.801404,None,0.115226
1,Agencourt,21,49,74,320,323,135,90,74,86,62,73,LE PEN,Emmanuel MACRON,droite,droite,17.093613,None,0.124492
2,Agey,21,42,51,252,244,82,49,72,99,56,45,MACRON,Jean-Luc MÉLENCHON,droite,gauche,17.093613,None,0.124492

In [82]:
#Indicateur d'emploi 2022
Indic_Emploi_2022 = pd.read_excel(r"C:\Users\33629\Desktop\data_mspr_bdd\Indicateur_Emploi_divis.xlsx", sheet_name = '2022')

In [83]:
Indic_Emploi_2022

   Code du département  Indic_2022
0                   21   15.991445
1                   58   16.783316
2                   71   18.663772
3                   89   17.925775

In [84]:
df_Vote['Code du département'] = df_Vote['Code du département'].astype(str)
Indic_Emploi_2022['Code du département'] = Indic_Emploi_2022['Code du département'].astype(str)

# Merge df_Vote et Indic_Emploi_2022 basé sur la colonne 'Code du département' dans df_Vote et 'Code du département' dans Indic_Emploi_2022
pivot_2022_emploi = df_Vote.merge(Indic_Emploi_2022[['Code du département', 'Indic_2022']], on='Code du département', how='left')

In [85]:
# Remplir la colonne 'Indicateur_Emploi_2017' dans df_Vote avec les valeurs correspondantes de 'Indic_2017' dans Indic_Emploi_2017
df_Vote['Indicateur_Emploi_2022'] = pivot_2022_emploi['Indic_2022']

In [86]:
df_Vote.head(3)

,Libellé de la commune,Code du département,Votes_Nuls_2017,Votes_Nuls_2022,Inscrits_2017,Inscrits_2022,Droite_2017,Droite_2022,Gauche_2017,Gauche_2022,Milieu_2017,Milieu_2022,Gagnants_2017,Gagnants_2022,Partie_Gagnante_2017,Partie_Gagnante_2022,Indicateur_Emploi_2017,Indicateur_Emploi_2022,Indicateur_Crime
0,Achun,58,16,26,108,105,47,47,25,18,20,14,LE PEN,Marine LE PEN,droite,droite,17.801404,16.783316,0.115226
1,Agencourt,21,49,74,320,323,135,90,74,86,62,73,LE PEN,Emmanuel MACRON,droite,droite,17.093613,15.991445,0.124492
2,Agey,21,42,51,252,244,82,49,72,99,56,45,MACRON,Jean-Luc MÉLENCHON,droite,gauche,17.093613,15.991445,0.124492

In [96]:
df_Vote

,Libellé de la commune,Code du département,Votes_Nuls_2017,Votes_Nuls_2022,Inscrits_2017,Inscrits_2022,Droite_2017,Droite_2022,Gauche_2017,Gauche_2022,Milieu_2017,Milieu_2022,Gagnants_2017,Gagnants_2022,Partie_Gagnante_2017,Partie_Gagnante_2022,Indicateur_Emploi_2017,Indicateur_Emploi_2022,Indicateur_Crime
0,Achun,58,16,26,108,105,47,47,25,18,20,14,LE PEN,Marine LE PEN,droite,droite,17.801404,16.783316,0.115226
1,Agencourt,21,49,74,320,323,135,90,74,86,62,73,LE PEN,Emmanuel MACRON,droite,droite,17.093613,15.991445,0.124492
2,Agey,21,42,51,252,244,82,49,72,99,56,45,MACRON,Jean-Luc MÉLENCHON,droite,gauche,17.093613,15.991445,0.124492
3,Ahuy,21,164,164,1000,618,441,199,161,99,234,156,FILLON,Emmanuel MACRON,droite,droite,17.093613,15.991445,0.124492
4,Aignay-le-Duc,21,60,98,248,659,115,204,33,169,40,188,FILLON,Emmanuel MACRON,droite,droite,17.093613,15.991445,0.124492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2003,Voudenay,21,10,193,114,766,46,228,34,166,24,179,LE PEN,Emmanuel MACRON,droite,droite,17.093613,15.991445,0.124492
2004,Vougeot,21,32,157,137,649,69,184,24,162,12,146,LE PEN,Emmanuel MACRON,droite,droite,17.093613,15.991445,0.124492
2005,Voulaines-les-Templiers,21,76,39,383,192,186,59,74,26,47,68,LE PEN,Emmanuel MACRON,droite,milieu,17.093613,15.991445,0.124492
2006,Voutenay-sur-Cure,89,18,20,79,69,39,28,14,16,8,5,FILLON,Marine LE PEN,droite,droite,18.668887,17.925775,0.141275
2007,Yrouerre,89,16,76,165,385,96,158,31,79,22,72,LE PEN,Marine LE PEN,droite,droite,18.668887,17.925775,0.141275

In [97]:
df_Vote.to_clipboard()